// <auto-generated />
using Academy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Academy.Migrations
{
    [DbContext(typeof(AcademyContext))]
    [Migration("20251018165447_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Academy.Models.Direction", b =>
                {
                    b.Property<int>("direction_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("direction_id"));

                    b.Property<string>("direction_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("direction_id");

                    b.ToTable("Directions");
                });

            modelBuilder.Entity("Academy.Models.Discipline", b =>
                {
                    b.Property<short>("discipline_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("discipline_id"));

                    b.Property<string>("discipline_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("number_of_lessons")
                        .HasColumnType("tinyint");

                    b.HasKey("discipline_id");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("Academy.Models.Group", b =>
                {
                    b.Property<int>("group_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("group_id"));

                    b.Property<int>("direction_id")
                        .HasColumnType("int");

                    b.Property<string>("group_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("group_id");

                    b.HasIndex("direction_id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Academy.Models.Student", b =>
                {
                    b.Property<int>("student_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("student_id"));

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("group_id")
                        .HasColumnType("int");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("student_id");

                    b.HasIndex("group_id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Academy.Models.Teacher", b =>
                {
                    b.Property<int>("teacher_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("teacher_id"));

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("teacher_id");

                    b.ToTable("Teachers");
                });

            modelBuilder.Entity("Academy.Models.Group", b =>
                {
                    b.HasOne("Academy.Models.Direction", "Direction")
                        .WithMany("Groups")
                        .HasForeignKey("direction_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Direction");
                });

            modelBuilder.Entity("Academy.Models.Student", b =>
                {
                    b.HasOne("Academy.Models.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("group_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Academy.Models.Direction", b =>
                {
                    b.Navigation("Groups");
                });

            modelBuilder.Entity("Academy.Models.Group", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
